2014/09/23 11:48:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:21:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:23:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:27:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:33:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 15:55:44 [error] [exception.CException] exception 'CException' with message 'SiteController and its behaviors do not have a method or closure named "creatUrl".' in C:\xampp\htdocs\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(59): CComponent->__call('creatUrl', Array)
#1 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(59): SiteController->creatUrl('Site/Login')
#2 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\loei\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\loei\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/loei/index.php
---
2014/09/24 11:28:58 [error] [exception.CException] exception 'CException' with message 'CWebApplication and its behaviors do not have a method or closure named "getState".' in C:\xampp\htdocs\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(68): CComponent->__call('getState', Array)
#1 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(68): CWebApplication->getState('fullname')
#2 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\loei\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\loei\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/loei/index.php
HTTP_REFERER=http://localhost:89/loei/index.php?r=Site/Login
---
2014/09/24 13:16:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('User/admin')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=User/admin
---
2014/09/24 13:17:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=user/admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=User/index
---
2014/09/24 13:23:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=user/create
---
2014/09/24 13:39:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('update')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=user/update&id=admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=User/admin
---
2014/09/24 17:21:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('Admin')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/Admin')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=Patient/Admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=site/login
---
2014/09/24 17:49:27 [error] [exception.CException] exception 'CException' with message 'คุณสมบัติ "Patient.id" ยังไม่ถูกกำหนด' in C:\xampp\htdocs\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\framework\base\CComponent.php(612) : eval()'d code(1): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\framework\zii\widgets\grid\CDataColumn.php(137): CComponent->evaluateExpression('CHtml::link($da...', Array)
#4 C:\xampp\htdocs\framework\zii\widgets\grid\CGridColumn.php(151): CDataColumn->renderDataCellContent(0, Object(Patient))
#5 C:\xampp\htdocs\framework\zii\widgets\grid\CGridView.php(616): CGridColumn->renderDataCell(0)
#6 C:\xampp\htdocs\framework\zii\widgets\grid\CGridView.php(572): CGridView->renderTableRow(0)
#7 C:\xampp\htdocs\framework\zii\widgets\grid\CGridView.php(482): CGridView->renderTableBody()
#8 C:\xampp\htdocs\framework\zii\widgets\CBaseListView.php(167): CGridView->renderItems()
#9 [internal function]: CBaseListView->renderSection(Array)
#10 C:\xampp\htdocs\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{item...')
#11 C:\xampp\htdocs\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#12 C:\xampp\htdocs\framework\web\CBaseController.php(173): CBaseListView->run()
#13 C:\xampp\htdocs\loei\themes\mytheme\views\patient\admin.php(69): CBaseController->widget('booster.widgets...', Array)
#14 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#15 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#16 C:\xampp\htdocs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#17 C:\xampp\htdocs\framework\web\CController.php(782): CController->renderPartial('admin', Array, true)
#18 C:\xampp\htdocs\loei\protected\controllers\PatientController.php(137): CController->render('admin', Array)
#19 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): PatientController->actionAdmin()
#20 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#21 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#22 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#23 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#24 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#25 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#27 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#28 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('Admin')
#29 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/Admin')
#30 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#31 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#32 {main}
REQUEST_URI=/loei/index.php?r=Patient/Admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=User/Admin
---
2014/09/25 09:40:17 [error] [exception.CException] exception 'CException' with message 'Patient and its behaviors do not have a method or closure named "getData".' in C:\xampp\htdocs\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(227): CComponent->__call('getData', Array)
#1 C:\xampp\htdocs\framework\zii\widgets\CBaseListView.php(111): CActiveRecord->__call('getData', Array)
#2 C:\xampp\htdocs\framework\zii\widgets\CBaseListView.php(111): Patient->getData()
#3 C:\xampp\htdocs\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#4 C:\xampp\htdocs\loei\protected\extensions\booster\widgets\TbGridView.php(68): CGridView->init()
#5 C:\xampp\htdocs\framework\web\CBaseController.php(147): TbGridView->init()
#6 C:\xampp\htdocs\framework\web\CBaseController.php(172): CBaseController->createWidget('booster.widgets...', Array)
#7 C:\xampp\htdocs\loei\themes\mytheme\views\patient\admin.php(69): CBaseController->widget('booster.widgets...', Array)
#8 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#9 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#11 C:\xampp\htdocs\framework\web\CController.php(782): CController->renderPartial('admin', Array, true)
#12 C:\xampp\htdocs\loei\protected\controllers\PatientController.php(137): CController->render('admin', Array)
#13 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): PatientController->actionAdmin()
#14 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('admin')
#23 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('patient/admin')
#24 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#25 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/loei/index.php?r=patient/admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=Patient/Update&id=wddsad
---
2014/09/25 10:04:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('patient/update')
#10 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/loei/index.php?r=patient/update&id=sssdsd
HTTP_REFERER=http://localhost:89/loei/index.php?r=patient/view&id=sssdsd
---
2014/09/25 10:05:05 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('patient/update')
#10 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/loei/index.php?r=patient/update&id=wddsad
HTTP_REFERER=http://localhost:89/loei/index.php?r=patient/view&id=wddsad
---
2014/09/25 10:13:41 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Invalid request. Please do not repeat this request again.' in C:\xampp\htdocs\loei\protected\controllers\PatientController.php:113
Stack trace:
#0 [internal function]: PatientController->actionDelete('wddsad')
#1 C:\xampp\htdocs\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(PatientController), Array)
#2 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PatientController), Object(ReflectionMethod), Array)
#3 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('Delete')
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/Delete')
#13 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/loei/index.php?r=Patient/Delete&id=wddsad
HTTP_REFERER=http://localhost:89/loei/index.php?r=Patient/Update&cid=wddsad
---
2014/09/25 10:13:53 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Invalid request. Please do not repeat this request again.' in C:\xampp\htdocs\loei\protected\controllers\PatientController.php:113
Stack trace:
#0 [internal function]: PatientController->actionDelete('12111323')
#1 C:\xampp\htdocs\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(PatientController), Array)
#2 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PatientController), Object(ReflectionMethod), Array)
#3 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('Delete')
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/Delete')
#13 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/loei/index.php?r=Patient/Delete&id=12111323
HTTP_REFERER=http://localhost:89/loei/index.php?r=Patient/Update&cid=12111323
---
2014/09/25 10:14:45 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Invalid request. Please do not repeat this request again.' in C:\xampp\htdocs\loei\protected\controllers\PatientController.php:113
Stack trace:
#0 [internal function]: PatientController->actionDelete('12111323')
#1 C:\xampp\htdocs\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(PatientController), Array)
#2 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PatientController), Object(ReflectionMethod), Array)
#3 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('Delete')
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/Delete')
#13 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/loei/index.php?r=Patient/Delete&id=12111323
HTTP_REFERER=http://localhost:89/loei/index.php?r=Patient/Update&cid=12111323
---
2014/09/25 10:21:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\loei\protected\controllers\PatientController.php:154
Stack trace:
#0 C:\xampp\htdocs\loei\protected\controllers\PatientController.php(117): PatientController->loadModel('12111323')
#1 [internal function]: PatientController->actionDeleteCase('12111323')
#2 C:\xampp\htdocs\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(PatientController), Array)
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PatientController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('DeleteCase')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/DeleteC...')
#14 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/loei/index.php?r=Patient/DeleteCase&cid=12111323
HTTP_REFERER=http://localhost:89/loei/index.php?r=Patient/Update&cid=12111323
---
2014/09/25 10:22:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\loei\protected\controllers\PatientController.php:154
Stack trace:
#0 C:\xampp\htdocs\loei\protected\controllers\PatientController.php(82): PatientController->loadModel('sasdasd')
#1 [internal function]: PatientController->actionUpdate('sasdasd')
#2 C:\xampp\htdocs\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(PatientController), Array)
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PatientController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('Update')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/Update')
#14 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/loei/index.php?r=Patient/Update&cid=sasdasd
HTTP_REFERER=http://localhost:89/loei/index.php?r=Patient/Admin
---
2014/09/25 10:28:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "DeleteCase?cid=wddsad" ตามคำสั่งได้' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('DeleteCase?cid=...')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('DeleteCase?cid=...')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/DeleteC...')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=Patient/DeleteCase?cid=wddsad
HTTP_REFERER=http://localhost:89/loei/index.php?r=Patient/Update&cid=wddsad
---
