2014/09/23 11:48:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:21:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:23:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:27:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 13:33:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test3".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('test3')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('test3')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('app/test3')
#3 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/loei/index.php?r=app/test3
---
2014/09/23 15:55:44 [error] [exception.CException] exception 'CException' with message 'SiteController and its behaviors do not have a method or closure named "creatUrl".' in C:\xampp\htdocs\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(59): CComponent->__call('creatUrl', Array)
#1 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(59): SiteController->creatUrl('Site/Login')
#2 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\loei\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\loei\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/loei/index.php
---
2014/09/24 11:28:58 [error] [exception.CException] exception 'CException' with message 'CWebApplication and its behaviors do not have a method or closure named "getState".' in C:\xampp\htdocs\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(68): CComponent->__call('getState', Array)
#1 C:\xampp\htdocs\loei\themes\mytheme\views\layouts\main.php(68): CWebApplication->getState('fullname')
#2 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\loei\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\loei\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/loei/index.php
HTTP_REFERER=http://localhost:89/loei/index.php?r=Site/Login
---
2014/09/24 13:16:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('User/admin')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=User/admin
---
2014/09/24 13:17:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=user/admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=User/index
---
2014/09/24 13:23:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('create')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=user/create
---
2014/09/24 13:39:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('update')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=user/update&id=admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=User/admin
---
2014/09/24 17:21:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '???????????????...')
#1 C:\xampp\htdocs\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('Admin')
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('Patient/Admin')
#9 C:\xampp\htdocs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\loei\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/loei/index.php?r=Patient/Admin
HTTP_REFERER=http://localhost:89/loei/index.php?r=site/login
---
